/******************************************************************************
Title           : InterestCard.js
Author          : Alfonso Enriquez
Description     : A card that is generated by
Exports         : SimilarInterestsLayout
Child Components: InterestCard
******************************************************************************/

/******************************************************************************
  Libraries
******************************************************************************/


import React, { Component } from 'react';
import { Text, View} from 'react-native';
import ListOfSimilarUsers from './listOfSimilarUsers.js'
import * as firebase from "firebase";

export default class InterestCard extends Component {
  constructor(props){
    super(props);
    this.state = {
      userId: firebase.auth().currentUser,
      interest: this.props.interest,
      usersWithSimilarInterests: [],
      loading: true
    }
  }

  componentWillMount(){
    let ref =  firebase.database().ref('Luis_Activities/' + this.state.interest);

    let responseActivity = [];

    ref.on('value', (snapshot) => {
      snapshot.forEach((childSnapshot) => {
        let childData = childSnapshot.val();
        responseActivity.push(childData)
      });

      this.setState({
        usersWithSimilarInterests: responseActivity,
        loading: false
      })
    })
  }

  render(){
    return(
      <View>
        {this.state.loading ?
          (
            <Text>Now we are are querying for users with Similar Interets...</Text>):
          (
            <View>
              <Text> Interests One: {this.state.interest} </Text>
              <ListOfSimilarUsers similarUsersIds={this.state.usersWithSimilarInterests}/>
            </View>
          )
        }
      </View>
    )
  }
}
